---
- name: include lihas_common
  include_role:
    name: lihas_common
  when: role_done_lihas_common is not defined
- name: install software
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - check-mk-agent
  loop_control:
    loop_var: item

- name: enable check-mk-agent via systemd
  service:
    name: check_mk.socket
    enabled: true
    state: started
